# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/kb.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_dis_common_0_0_1/design_1_dis_common_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dis_common_0_0 || ORIG_REF_NAME==design_1_dis_common_0_0}]

# IP: bd/design_1/ip/design_1_dis_floor_0_0/design_1_dis_floor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dis_floor_0_0 || ORIG_REF_NAME==design_1_dis_floor_0_0}]

# IP: bd/design_1/ip/design_1_one_HZ_time_0_0_1/design_1_one_HZ_time_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_one_HZ_time_0_0 || ORIG_REF_NAME==design_1_one_HZ_time_0_0}]

# IP: bd/design_1/ip/design_1_dis_common_1_0/design_1_dis_common_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dis_common_1_0 || ORIG_REF_NAME==design_1_dis_common_1_0}]

# IP: bd/design_1/ip/design_1_dis_time_0_0/design_1_dis_time_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dis_time_0_0 || ORIG_REF_NAME==design_1_dis_time_0_0}]

# IP: bd/design_1/ip/design_1_controller_0_0/design_1_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_controller_0_0 || ORIG_REF_NAME==design_1_controller_0_0}]

# IP: bd/design_1/ip/design_1_one_three_0_0/design_1_one_three_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_one_three_0_0 || ORIG_REF_NAME==design_1_one_three_0_0}]

# IP: bd/design_1/ip/design_1_kb_0_0/design_1_kb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_kb_0_0 || ORIG_REF_NAME==design_1_kb_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
